var FormElement=Backbone.Model.extend({initialize:function(){this.set({"name":(typeof this.get("name")=="undefined")?this.get("label").toLowerCase().dasherize():this.name});},value:null,validate:function(b){var a=[];_.each(this.get("options"),function(c){switch(c.name){case"optional":if(c.value=="false"&&b.value==""){if(this.hasOwnProperty("init")){console.log("Error: value is empty ");
a.push(this.get("label")+" is required");}else{this.init="yes";}}break;case"absolute-min":break;case"absolute-max":if(parseInt(b.value)>parseInt(c.value)){a.push(this.get("label")+" is too high. Value: "+b.value+" Absolute Max value: "+c.value);}break;case"max":if(parseInt(b.value)>parseInt(c.value)){a.push(this.get("label")+" is too high. Value: "+b.value+" Max value: "+c.value);
}break;case"min":break;default:a.push("'"+this.option.name+"' not supported as a validation option");}},this);if(_.any(a)){this.trigger("validationError",a);return a;}else{return null;}},url:"/form_element"});

var FormElements=Backbone.Collection.extend({model:FormElement,url:"/formElements",validate:function(){var a=[];this.each(function(c){var b=c.get("datatype");if(b!="display"){console.log("validate:"+c.get("label")+" field value:"+c.get("value"));a.push(c.validate({value:c.get("value")}));}});console.log("validationErrors: "+a);
return _.compact(a);},valid:function(){return this.validate().length==0;}});

window.Form=Backbone.Model.extend({initialize:function(){this.formElements=new FormElements;},url:"/form",});

var FormCollection=Backbone.Collection.extend({model:Form,initialize:function(){},});

window.Page=Backbone.Model.extend({initialize:function(){}});

window.FormElementView=Backbone.View.extend({tagName:"td",template:Handlebars.compile($("#form-element-template").html()),initialize:function(){this.model.bind("validationError",this.showErrorMessages,this);this.model.view=this;},events:{"change":"validate"},validate:function(){this.$(".error-message").html("").hide();
this.inputType=this.model.get("inputType");console.log("inputType: "+this.inputType);this.currentValue=this.$("input").val();if(this.inputType=="dropdown"){this.currentValue=this.$("select").val();}else{if(this.inputType=="dropdown-add-one"){this.currentValue=this.$("select").val();}else{if(this.inputType=="selectFDA"){this.currentValue=this.$("select").val();
}else{if(this.inputType=="selectCascadeParent"){this.currentValue=this.$("select").val();}else{if(this.inputType=="selectCascadeChild"){this.currentValue=this.$("select").val();}else{if(this.inputType=="checkbox"){this.currentValue=this.$("checkbox").val();}}}}}}console.log("FormElementView validate currentValue: "+this.currentValue);
this.validationResult=this.model.validate({value:this.currentValue});if(this.validationResult==null){}else{console.log("validation error: "+this.validationResult);}return this.validationResult;},changeSelected:function(){this.inputType=this.model.get("inputType");},render:function(){this.colspan=this.model.get("colspan");
if(this.colspan==null){this.colspan=1;}$(this.el).attr("colspan",this.colspan);var a=$(this.el).attr("id");var b=this.template(this.model.toJSON());$(this.el).html(b);return this;},showErrorMessages:function(a){this.$(".error-message").html(a.join(". ")).show();},});
window.RecordElementView=Backbone.View.extend({tagName:"td",template:Handlebars.compile($("#record-element-template").html()),initialize:function(){this.model.bind("validationError",this.showErrorMessages,this);this.model.view=this;},render:function(){this.colspan=this.model.get("colspan");if(this.colspan==null){this.colspan=1;
}$(this.el).attr("colspan",this.colspan);var a=$(this.el).attr("id");var b=this.template(this.model.toJSON());$(this.el).html(b);return this;},});
var FormView=Backbone.View.extend({template:loadTemplate("form.template.html"),initialize:function(){_.bindAll(this,"render","addOne","saveRecord","remove");this.bind("reset",this.updateView);return this;},remove:function(){console.log("remove the view in FormView");$(this.el).remove();},clear:function(){console.log("clear(destroy) the view");
this.model.destroy();},updateView:function(){console.log("updateView");this.remove();this.render();},render:function(){if(window.orientation==-90){this.orientation="vert";}else{this.orientation="vert";}if(this.orientation==="vert"){this.template=loadTemplate("form.vert.template.html");}else{this.template=loadTemplate("form.vert.template.html");
}this.form=this.options.currentForm;this.parentId=this.options.currentForm.parentId;$(this.el).html(this.template(this.form.toJSON()));var c=this.options.currentForm.get("flow");var b=c.id;var j=this.options.currentForm.get("_id");var f=this.options.currentForm.get("assignedId");var e=this.options.currentForm.get("createdWidget");
this.formElements=new FormElements(this.options.currentForm.get("form_elements"),{view:this});var d={"label":"parentIdWidget","value":this.parentId,"identifier":"parentId","inputType":"hidden"};var n={"label":"flowIdWidget","value":b,"identifier":"flowId","inputType":"hidden"};var k={"label":"formIdWidget","value":j,"identifier":"formId","inputType":"hidden"};
var m={"label":"assignedIdWidget","value":f,"identifier":"assignedId","inputType":"hidden"};var a={"label":"createdWidget","value":e,"identifier":"created","inputType":"hidden"};this.formElements.add(d,{at:0});this.formElements.add(n,{at:1});this.formElements.add(k,{at:2});this.formElements.add(m,{at:3});
this.formElements.add(a,{at:4});var i=this.model.get("_id");if(i!=null){var l={"label":"idWidget","value":i,"identifier":"_id","inputType":"hidden"};this.formElements.add(l,{at:4});}var h=this.model.get("_rev");if(h!=null){var g={"label":"revWidget","value":h,"identifier":"_rev","inputType":"hidden"};
this.formElements.add(g,{at:5});}this.formElements.each(this.addOne);return this;},currentParentName:"formElements",currentParent:$(this.currentParentName),currentTableName:"",currentRow:0,formElements:null,addOne:function(g){var f=g.get("inputType");var e=g.get("datatype");var a=g.get("closeRow");var b=g.get("identifier");
var d=g.get("cols");var c=g.get("size");this.value=this.model.get(b);if((f!=="hidden")&&(e!=="display")){this.currentRow++;}if(this.value!=null){g.set({"value":this.value});g.set({"recordValue":this.value});}if(this.orientation==="vert"){d=2;if(a==="false"){if(this.currentRow%2){a="false";}else{a="true";
}}if(f=="button"){a="true";}else{if(f=="text"){if(c>25){a="true";g.set({"colspan":"2"});if(c>=50){g.set({"size":"50"});}}}else{if(f=="textarea"){a="true";}else{g.set({"colspan":"1"});}}}}if(d==null){if(this.orientation==="vert"){d=2;}else{d=3;}}if(f=="display-tbl-begin"){template=displayTableWidgetCompiledHtml;
html=template(g.toJSON());$("#formElements").append(html);currentParentName="#beginTableRow"+b;currentParent=$(currentParentName);currentTableName="#beginTableRow"+b;}else{if(f=="display-tbl-end"){}else{if(f=="hidden-empty"){html="<input id='"+b+"'name='"+b+"' type='hidden'></input>";$(this.$("#formElements")).append(html);
}else{if(f=="hidden-preset"){html="<input id='"+b+"'name='"+b+"' type='hidden'></input>";$(this.$("#formElements")).append(html);}else{if(f=="display-header"){g.set({"tblCols":d});currentParent.append((new FormElementView({model:g})).render().el);}else{if(f=="hidden"){currentParentName="#theForm";currentParent=$(currentParentName);
a="false";$(this.$("#formElements")).append((new FormElementView({model:g})).render().el);}else{currentParent.append((new FormElementView({model:g})).render().el);}}}}}}if(a=="true"){$(currentTableName).append('<tr id="row'+b+'"></tr>');currentParentName="#row"+b;currentParent=$(currentParentName);this.currentRow=0;
}},events:{"click #form-save":"saveRecord",},saveRecord:function(f){f.preventDefault();console.log("validating the form submission.");var j=[];this.formElements.each(function(l){var k=l.get("datatype");if(k!="display"){var e=$("#"+l.get("identifier")).val();j.push(l.validate({value:e}));}});var h=_.compact(j);
if(h.length==0){console.log("Ready to save");var b=$("#theForm").toObject();var i=$("#formId").val();console.log("formData: "+JSON.stringify(b));var g=b._id;if(g==null){var d=Math.round(+new Date()/1000);b.created=d;console.log("formData.created: "+b.created);b.lastModified=b.created;if(i==="incident"){var a=$.couch.db(Backbone.couch_connector.config.db_name).info({success:function(l){console.log("info: "+JSON.stringify(l));
var k=l["doc_count"];var m=l["doc_del_count"];var e=k+m;console.log("assignedId: "+e);b.assignedId=e.toString();console.log("FORMY.Incidents.create(formData);"+JSON.stringify(b));FORMY.Incidents.create(b,{success:function(n,o){nextModel=n;FORMY.sessionRecord=n;inspectModelAndGo(n);},error:function(){console.log("Error saving: "+arguments);
}});}});}else{console.log("Saving the record using FORMY.sessionRecord.records.create");FORMY.sessionRecord.records.create(b,{success:function(e,k){console.log("added new record to FORMY.sessionRecord.records.");inspectModelAndGo(e);},error:function(){console.log("Error saving: "+arguments);}});}}else{var d=Math.round(+new Date()/1000);
b.lastModified=d;console.log("Updating the record using record.save");var c=new Record(b);c.collection="patient-records";c.urlRoot="patient-records";c.save({},{success:function(e,k){console.log("Updated the record.");inspectModelAndGo(e);},error:function(){console.log("Error saving: "+JSON.stringify(arguments));
}});}this.options.currentForm=null;this.form=null;}else{console.log("Errors:"+JSON.stringify(h));alert(h);}},});function inspectModelAndGo(a){var c=null;var d=null;var b=null;var e=null;if((typeof a.get!=="undefined")&&(typeof a.get("formId")!=="undefined")){d=a.get("formId");}else{d=a.formId;}if((typeof a.get!=="undefined")&&(typeof a.get("_id")!=="undefined")){b=a.get("_id");
}else{b=a._id;}if((typeof a.get!=="undefined")&&(typeof a.get("parentId")!=="undefined")){e=a.get("parentId");}else{e=a.parentId;}if(d==="incident"){c=b;}else{c=e;}FORMY.router.navigate("home",true);}

window.RecordElementView=Backbone.View.extend({tagName:"td",template:Handlebars.compile($("#record-element-template").html()),initialize:function(){this.model.bind("validationError",this.showErrorMessages,this);this.model.view=this;},render:function(){this.colspan=this.model.get("colspan");if(this.colspan==null){this.colspan=1;
}$(this.el).attr("colspan",this.colspan);var a=$(this.el).attr("id");var b=this.template(this.model.toJSON());$(this.el).html(b);return this;},});

var FormView=Backbone.View.extend({template:loadTemplate("form.template.html"),initialize:function(){_.bindAll(this,"render","addOne","saveRecord","remove");this.bind("reset",this.updateView);return this;},remove:function(){console.log("remove the view in FormView");$(this.el).remove();},clear:function(){console.log("clear(destroy) the view");
this.model.destroy();},updateView:function(){console.log("updateView");this.remove();this.render();},render:function(){if(window.orientation==-90){this.orientation="vert";}else{this.orientation="vert";}if(this.orientation==="vert"){this.template=loadTemplate("form.vert.template.html");}else{this.template=loadTemplate("form.vert.template.html");
}this.form=this.options.currentForm;this.parentId=this.options.currentForm.parentId;$(this.el).html(this.template(this.form.toJSON()));var c=this.options.currentForm.get("flow");var b=c.id;var j=this.options.currentForm.get("_id");var f=this.options.currentForm.get("assignedId");var e=this.options.currentForm.get("createdWidget");
this.formElements=new FormElements(this.options.currentForm.get("form_elements"),{view:this});var d={"label":"parentIdWidget","value":this.parentId,"identifier":"parentId","inputType":"hidden"};var n={"label":"flowIdWidget","value":b,"identifier":"flowId","inputType":"hidden"};var k={"label":"formIdWidget","value":j,"identifier":"formId","inputType":"hidden"};
var m={"label":"assignedIdWidget","value":f,"identifier":"assignedId","inputType":"hidden"};var a={"label":"createdWidget","value":e,"identifier":"created","inputType":"hidden"};this.formElements.add(d,{at:0});this.formElements.add(n,{at:1});this.formElements.add(k,{at:2});this.formElements.add(m,{at:3});
this.formElements.add(a,{at:4});var i=this.model.get("_id");if(i!=null){var l={"label":"idWidget","value":i,"identifier":"_id","inputType":"hidden"};this.formElements.add(l,{at:4});}var h=this.model.get("_rev");if(h!=null){var g={"label":"revWidget","value":h,"identifier":"_rev","inputType":"hidden"};
this.formElements.add(g,{at:5});}this.formElements.each(this.addOne);return this;},currentParentName:"formElements",currentParent:$(this.currentParentName),currentTableName:"",currentRow:0,formElements:null,addOne:function(g){var f=g.get("inputType");var e=g.get("datatype");var a=g.get("closeRow");var b=g.get("identifier");
var d=g.get("cols");var c=g.get("size");this.value=this.model.get(b);if((f!=="hidden")&&(e!=="display")){this.currentRow++;}if(this.value!=null){g.set({"value":this.value});g.set({"recordValue":this.value});}if(this.orientation==="vert"){d=2;if(a==="false"){if(this.currentRow%2){a="false";}else{a="true";
}}if(f=="button"){a="true";}else{if(f=="text"){if(c>25){a="true";g.set({"colspan":"2"});if(c>=50){g.set({"size":"50"});}}}else{if(f=="textarea"){a="true";}else{g.set({"colspan":"1"});}}}}if(d==null){if(this.orientation==="vert"){d=2;}else{d=3;}}if(f=="display-tbl-begin"){template=displayTableWidgetCompiledHtml;
html=template(g.toJSON());$("#formElements").append(html);currentParentName="#beginTableRow"+b;currentParent=$(currentParentName);currentTableName="#beginTableRow"+b;}else{if(f=="display-tbl-end"){}else{if(f=="hidden-empty"){html="<input id='"+b+"'name='"+b+"' type='hidden'></input>";$(this.$("#formElements")).append(html);
}else{if(f=="hidden-preset"){html="<input id='"+b+"'name='"+b+"' type='hidden'></input>";$(this.$("#formElements")).append(html);}else{if(f=="display-header"){g.set({"tblCols":d});currentParent.append((new FormElementView({model:g})).render().el);}else{if(f=="hidden"){currentParentName="#theForm";currentParent=$(currentParentName);
a="false";$(this.$("#formElements")).append((new FormElementView({model:g})).render().el);}else{currentParent.append((new FormElementView({model:g})).render().el);}}}}}}if(a=="true"){$(currentTableName).append('<tr id="row'+b+'"></tr>');currentParentName="#row"+b;currentParent=$(currentParentName);this.currentRow=0;
}},events:{"click #form-save":"saveRecord",},saveRecord:function(f){f.preventDefault();console.log("validating the form submission.");var j=[];this.formElements.each(function(l){var k=l.get("datatype");if(k!="display"){var e=$("#"+l.get("identifier")).val();j.push(l.validate({value:e}));}});var h=_.compact(j);
if(h.length==0){console.log("Ready to save");var b=$("#theForm").toObject();var i=$("#formId").val();console.log("formData: "+JSON.stringify(b));var g=b._id;if(g==null){var d=Math.round(+new Date()/1000);b.created=d;console.log("formData.created: "+b.created);b.lastModified=b.created;if(i==="incident"){var a=$.couch.db(Backbone.couch_connector.config.db_name).info({success:function(l){console.log("info: "+JSON.stringify(l));
var k=l["doc_count"];var m=l["doc_del_count"];var e=k+m;console.log("assignedId: "+e);b.assignedId=e.toString();console.log("FORMY.Incidents.create(formData);"+JSON.stringify(b));FORMY.Incidents.create(b,{success:function(n,o){nextModel=n;FORMY.sessionRecord=n;inspectModelAndGo(n);},error:function(){console.log("Error saving: "+arguments);
}});}});}else{console.log("Saving the record using FORMY.sessionRecord.records.create");FORMY.sessionRecord.records.create(b,{success:function(e,k){console.log("added new record to FORMY.sessionRecord.records.");inspectModelAndGo(e);},error:function(){console.log("Error saving: "+arguments);}});}}else{var d=Math.round(+new Date()/1000);
b.lastModified=d;console.log("Updating the record using record.save");var c=new Record(b);c.collection="patient-records";c.urlRoot="patient-records";c.save({},{success:function(e,k){console.log("Updated the record.");inspectModelAndGo(e);},error:function(){console.log("Error saving: "+JSON.stringify(arguments));
}});}this.options.currentForm=null;this.form=null;}else{console.log("Errors:"+JSON.stringify(h));alert(h);}},});function inspectModelAndGo(a){var c=null;var d=null;var b=null;var e=null;if((typeof a.get!=="undefined")&&(typeof a.get("formId")!=="undefined")){d=a.get("formId");}else{d=a.formId;}if((typeof a.get!=="undefined")&&(typeof a.get("_id")!=="undefined")){b=a.get("_id");
}else{b=a._id;}if((typeof a.get!=="undefined")&&(typeof a.get("parentId")!=="undefined")){e=a.get("parentId");}else{e=a.parentId;}if(d==="incident"){c=b;}else{c=e;}FORMY.router.navigate("home",true);}

var HomeView=Backbone.View.extend({template:loadTemplate("home.template.html"),initialize:function(){_.bindAll(this,"addOne","reseted","render","search","orientation","nextLink");FORMY.Incidents.bind("add",this.addOne,this);FORMY.Incidents.bind("reset",this.reseted,this);FORMY.Incidents.bind("all",this.render,this);
FORMY.Incidents.bind("change",this.search,this);FORMY.Incidents.bind("render",this.render,this);return this;},startkey:null,startkey_docid:null,endkey_docid:null,addOne:function(a){this.view=new SearchListItemView({model:a});this.rendered=this.view.render().el;$("#incidents").append(this.rendered);},events:{"click #form-search ":"search","click #form-client ":"incidentLink","click #form-parto ":"partoLink","click #form-config ":"configLink","click #form-design ":"designLink","click #nextLink":"nextLink","orientationEvent ":"orientation",},reseted:function(){console.log("reseted; Incidents count: "+FORMY.Incidents.length);
$(this.el).html("");FORMY.Incidents.each(this.addOne);},remove:function(){console.log("remove the view in homeView");$(this.el).remove();},nextLink:function(){console.log("this.model.toJSON(): "+this.model.get("startkey"));if(this.model.get("startkey")!=null){FORMY.router.navigate("home/"+this.model.get("startkey")+"/"+this.model.get("startkey_docid"),true);
}else{console.log("nextLink");}},incidentLink:function(){FORMY.router.navigate("incident",true);},partoLink:function(){FORMY.router.navigate("parto",true);},configLink:function(){FORMY.router.navigate("config",true);},designLink:function(){FORMY.router.navigate("design",true);},search:function(c){c.preventDefault();
console.log("Searching");var a=$("#search_string").val();var b=$("#department").val();if(a==""&&b==""){FORMY.router.navigate("home",true);}else{FORMY.router.navigate("search/"+a+"/"+b,true);}},orientation:"horiz",render:function(){if(window.orientation==-90){this.orientation="vert";this.template=loadTemplate("home.vert.template.html");
}else{this.orientation="horiz";this.template=loadTemplate("home.vert.template.html");}var a=this.template(this.model.toJSON());console.log("rendering HomeView in coconut-formy");$("#homePageView").html(a);FORMY.Incidents.each(this.addOne);$(".stripeMe tr").mouseover(function(){$(this).addClass("over");}).mouseout(function(){$(this).removeClass("over");
});$(".stripeMe tr:even").addClass("alt");return this;},});var SearchListItemView=Backbone.View.extend({tagName:"tr",template:Handlebars.compile($("#search-template").html()),initialize:function(){_.bindAll(this,"render");this.model.bind("change",this.render);},render:function(){this.content=this.model.toJSON();
this.html=this.template(this.content);$(this.el).html(this.html);return this;}});

var ConfigView=Backbone.View.extend({template:loadTemplate("config.template.html"),initialize:function(){return this;},events:{"click #form-client ":"incidentLink","click #form-config ":"configLink","click #form-design ":"designLink","orientationEvent ":"orientation",},reseted:function(){console.log("reseted.");
},remove:function(){console.log("remove the view in homeView");$(this.el).remove();},incidentLink:function(){FORMY.router.navigate("incident",true);},configLink:function(){window.location.href="/mobilefuton/_design/mobilefuton/index.html";},designLink:function(){FORMY.router.navigate("design",true);},orientation:"horiz",render:function(){var a=this.template(this.model.toJSON());
console.log("rendering ConfigView");$("#homePageView").html(a);return this;},});

var Record=Backbone.Model.extend({});

var PatientRecordList=Backbone.Collection.extend({model:Record,initialize:function(){return this;},db:{view:"byPatientId",},url:"/patient-records",});

var Incident=Backbone.Model.extend({initialize:function(){this.records=new IncidentRecordList;},});

var IncidentsList=Backbone.Collection.extend({initialize:function(){this.page=1;},db:{view:"byId",},url:"/incident",model:Incident});

var IncidentRecordList=Backbone.Collection.extend({model:Record,initialize:function(){return this;},db:{view:"byParentId",},url:"/incident-records",});

window.IncidentView=Backbone.View.extend({el:$("#recordView"),template:loadTemplate("patient.template.html"),initialize:function(){_.bindAll(this,"render","addOne");return this;},render:function(){if(window.orientation==-90){this.orientation="vert";this.template=loadTemplate("patient.vert.template.html");
}else{this.orientation="horiz";this.template=loadTemplate("patient.vert.template.html");}thisHtml=this.template(this.model.toJSON());$("#recordView").html(thisHtml);FORMY.sessionRecord.records.each(this.addOne);console.log("sessionRecord: "+JSON.stringify(FORMY.sessionRecord));return this;},addOne:function(a){this.view=new RecordListItemView({model:a});
this.rendered=this.view.render().el;$("#records").append(this.rendered);},events:{},clientLink:function(){FORMY.router.navigate("newPatient",true);},homeLink:function(){FORMY.router.navigate("home",true);},docketLink:function(){FORMY.router.navigate("arrestDocket/"+FORMY.sessionRecord.get("_id"),true);
},});var RecordListItemView=Backbone.View.extend({tagName:"tr",template:Handlebars.compile($("#record-template").html()),initialize:function(){},render:function(){var b=this.model.toJSON();var a=this.template(b);$(this.el).html(a);console.log("render RecordListItemView: "+JSON.stringify(b));return this;
}});

window.RecordView=Backbone.View.extend({template:loadTemplate("record.template.html"),initialize:function(){_.bindAll(this,"render","addOne");return this;},render:function(){if(window.orientation==-90){this.orientation="vert";this.template=loadTemplate("record.vert.template.html");}else{this.orientation="vert";
this.template=loadTemplate("record.vert.template.html");}this.form=this.options.currentForm;this.patientId=this.options.currentForm.patientId;var b=this.options.currentForm.get("flow");var c=b.id;var f=this.options.currentForm.get("_id");var g=this.options.model.created;this.formElements=new FormElements(this.options.currentForm.get("form_elements"),{view:this});
var e={"label":"patientIdWidget","value":this.patientId,"identifier":"patientId","inputType":"hidden"};var d={"label":"flowIdWidget","value":c,"identifier":"flowId","inputType":"hidden"};var a={"label":"formIdWidget","value":f,"identifier":"formId","inputType":"hidden"};this.formElements.add(e,{at:0});
this.formElements.add(d,{at:1});this.formElements.add(a,{at:2});thisHtml=this.template(this.form.toJSON());$(this.el).html(thisHtml);this.formElements.each(this.addOne);return this;},currentParentName:"formElements",currentParent:$(this.currentParentName),currentTableName:"",currentRow:0,formElements:null,addOne:function(g){var f=g.get("inputType");
var e=g.get("datatype");var a=g.get("closeRow");var b=g.get("identifier");var d=g.get("cols");var c=g.get("size");this.value=this.model.get(b);if((f!=="hidden")&&(e!=="display")){this.currentRow++;}if(this.value!=null){g.set({"value":this.value});}if(this.orientation==="vert"){d=2;if(a==="false"){if(this.currentRow%2){a="false";
}else{a="true";}}if(f=="button"){a="true";}else{if(f=="text"){if(c>25){a="true";g.set({"colspan":"2"});if(c>=50){g.set({"size":"50"});}}}else{if(f=="textarea"){a="true";g.set({"colspan":"2"});g.set({"rows":"4"});g.set({"cols":"60"});}else{g.set({"colspan":"1"});}}}}if(d==null){if(this.orientation==="vert"){d=2;
}else{d=3;}}if(f=="display-tbl-begin"){template=displayTableWidgetCompiledHtml;html=template(g.toJSON());$("#formElements").append(html);currentParentName="#beginTableRow"+b;currentParent=$(currentParentName);currentTableName="#beginTableRow"+b;}else{if(f=="display-tbl-end"){}else{if(f=="hidden-empty"){html="<!-- "+b+" -->";
$(this.$("#formElements")).append(html);}else{if(f=="hidden-preset"){html="<!-- "+b+" -->";$(this.$("#formElements")).append(html);}else{if(f=="display-header"){g.set({"tblCols":d});currentParent.append((new RecordElementView({model:g})).render().el);}else{if(f=="hidden"){currentParentName="#theForm";
currentParent=$(currentParentName);a="false";$(this.$("#formElements")).append((new RecordElementView({model:g})).render().el);}else{currentParent.append((new RecordElementView({model:g})).render().el);}}}}}}if(a=="true"){$(currentTableName).append('<tr id="row'+b+'"></tr>');currentParentName="#row"+b;
currentParent=$(currentParentName);this.currentRow=0;}},});

var PartoView=Backbone.View.extend({template:loadTemplate("parto.template.html"),initialize:function(){_.bindAll(this,"render");return this;},render:function(){if(window.orientation==-90){this.orientation="vert";this.template=loadTemplate("parto.template.html");}else{this.orientation="horiz";this.template=loadTemplate("parto.template.html");
}var a=this.template(this.model.toJSON());console.log("rendering PartoView");$("#partoView").html(a);return this;},});

